import { OPENSTATUS_THEME } from "./openstatus";
import type { Theme } from "./types";

// Neutral ground; colour is reserved for the service states the page reports.
export const OEFFIGO_THEME = {
  id: "oeffigo" as const,
  name: "ÖffiGo",
  author: { name: "ÖffiGo", url: "https://oeffigo.app" },
  light: {
    ...OPENSTATUS_THEME.light,
    "--radius": "0.75rem",
    "--background": "#f4f5f7",
    "--foreground": "#0b0c0f",
    "--card": "#ffffff",
    "--card-foreground": "#0b0c0f",
    "--popover": "#ffffff",
    "--popover-foreground": "#0b0c0f",
    "--primary": "#0b0c0f",
    "--primary-foreground": "#ffffff",
    "--secondary": "#eceef1",
    "--secondary-foreground": "#0b0c0f",
    "--muted": "#eceef1",
    "--muted-foreground": "#5a616c",
    "--accent": "#eceef1",
    "--accent-foreground": "#0b0c0f",
    "--border": "#dcdfe4",
    "--input": "#cdd1d7",
    "--ring": "#9aa0a9",
    "--success": "#0b7a45",
    "--warning": "#955700",
    "--destructive": "#c42b1c",
    "--info": "#4c55d6",
  },
  dark: {
    ...OPENSTATUS_THEME.dark,
    "--radius": "0.75rem",
    "--background": "#000000",
    "--foreground": "#f4f5f7",
    "--card": "#0a0b0d",
    "--card-foreground": "#f4f5f7",
    "--popover": "#0f1013",
    "--popover-foreground": "#f4f5f7",
    "--primary": "#f4f5f7",
    "--primary-foreground": "#000000",
    "--secondary": "#131417",
    "--secondary-foreground": "#f4f5f7",
    "--muted": "#131417",
    "--muted-foreground": "#8e939c",
    "--accent": "#16171b",
    "--accent-foreground": "#f4f5f7",
    "--border": "#1d1f23",
    "--input": "#2a2c31",
    "--ring": "#4a4e56",
    "--success": "#34d17a",
    "--warning": "#ffb020",
    "--destructive": "#ff5c57",
    "--info": "#8b93ff",
  },
} as const satisfies Theme;
