// Builds the AGPL source archive of the running build, without anything private.
//   node ops/source-archive.mjs <out.tar.gz>   archive the current directory (Docker build)
//   node ops/source-archive.mjs --check        apply the same rules to tracked files
import { execFileSync } from "node:child_process";
import {
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

/** Dependencies and build output: regenerated by the documented build. */
const GENERATED_DIRS = new Set([
  "node_modules",
  ".next",
  ".turbo",
  "dist",
  "coverage",
  "test-results",
  ".git",
]);
/** Agent, editor and assistant setup at any depth. */
const TOOLING_DIRS = new Set([
  ".claude",
  ".codex",
  ".cursor",
  ".opencode",
  ".windsurf",
  ".continue",
  ".aider",
  ".zed",
  ".vscode",
  ".idea",
  ".github",
]);
/** Operator notes and hosting setup that only exist at the repository root. */
const PRIVATE_ROOT = new Set(["Brain", "docs", ".railway", ".stacked.toml"]);
const SHIPPED_APPS = new Set(["dashboard", "status-page"]);
const PRIVATE_FILE =
  /^(?:(?:AGENTS|CLAUDE|GEMINI|CODEX|COPILOT)(?:\.[^/]*)?\.md|\.cursorrules|\.windsurfrules|\.mcp\.json|opencode\.jsonc?|\.env(?:\..*)?|.*\.(?:pem|key|p12|tsbuildinfo|log)|\.DS_Store)$/i;

export function isShipped(path) {
  const parts = path.split("/");
  if (PRIVATE_ROOT.has(parts[0])) return false;
  if (parts[0] === "apps" && parts[1] !== "_" && !SHIPPED_APPS.has(parts[1]))
    return false;
  if (parts[0] === ".git") return false;
  for (const part of parts.slice(0, -1))
    if (GENERATED_DIRS.has(part) || TOOLING_DIRS.has(part)) return false;
  return !PRIVATE_FILE.test(parts.at(-1));
}

/**
 * Independent of the rules above: if any of these reach the archive, a rule is
 * wrong and the build must stop instead of publishing it.
 */
const NEVER_PATH =
  /(?:^|\/)(?:AGENTS\.md|CLAUDE\.md|\.claude\/|\.github\/|\.env(?:$|\.)|node_modules\/)|^(?:Brain|docs|\.railway|\.git)\//i;
const NEVER_CONTENT = [
  /-----BEGIN [A-Z ]*PRIVATE KEY-----/,
  /\bop:\/\/[\w-]+\/[\w-]+/,
  /\/Users\/[a-z][\w.-]*\/(?:Projects|Documents|Desktop|Library)\//,
];
const REQUIRED = [
  "LICENSE",
  "README.md",
  "package.json",
  "pnpm-lock.yaml",
  "pnpm-workspace.yaml",
  "apps/status-page/package.json",
  "apps/dashboard/package.json",
  "ops/status-page.Dockerfile",
  "ops/dashboard.Dockerfile",
  "ops/source-archive.mjs",
];

function walk(dir, prefix = "") {
  const files = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      if (!isShipped(`${path}/_`)) continue;
      files.push(...walk(join(dir, entry.name), path));
    } else if (entry.isFile() && isShipped(path)) files.push(path);
  }
  return files;
}

export function guard(files, read) {
  const problems = [];
  for (const path of files) {
    if (NEVER_PATH.test(path)) problems.push(`private path: ${path}`);
    if (
      path.startsWith("apps/") &&
      !/^apps\/(?:dashboard|status-page)\//.test(path)
    )
      problems.push(`unrelated app: ${path}`);
    const content = read(path);
    if (content && NEVER_CONTENT.some((pattern) => pattern.test(content)))
      problems.push(`private content: ${path}`);
  }
  for (const path of REQUIRED)
    if (!files.includes(path)) problems.push(`missing: ${path}`);
  return problems;
}

function readText(path) {
  try {
    if (statSync(path).size > 2_000_000) return "";
    return readFileSync(path, "utf8");
  } catch {
    return "";
  }
}

function main() {
  const target = process.argv[2];
  if (!target) {
    console.error("usage: node ops/source-archive.mjs <out.tar.gz> | --check");
    process.exit(2);
  }
  const check = target === "--check";
  const files = check
    ? execFileSync("git", ["ls-files", "-z"], { encoding: "utf8" })
        .split("\0")
        .filter(Boolean)
        .filter(isShipped)
    : walk(".");
  files.sort();
  const problems = guard(files, readText);
  if (problems.length > 0) {
    console.error(
      `Source archive would ship private files:\n${problems.join("\n")}`,
    );
    process.exit(1);
  }
  if (check) {
    console.log(`Source archive rules OK (${files.length} files).`);
    return;
  }
  const temp = mkdtempSync(join(tmpdir(), "source-archive-"));
  try {
    const list = join(temp, "files");
    writeFileSync(list, `${files.join("\0")}\0`);
    execFileSync("tar", ["-czf", target, "--null", "-T", list], {
      stdio: "inherit",
    });
  } finally {
    rmSync(temp, { recursive: true, force: true });
  }
  console.log(`Source archive written (${files.length} files).`);
}

if (import.meta.url === `file://${process.argv[1]}`) main();
